### ISSUE TITLE
Sidekiq integration broke with Rails 6.0.2

### ISSUE THREAD

**Issue by pj0tr** [DataDog/dd-trace-rb#943] opened 2020-02-07 14:36 UTC
https://github.com/rails/rails/commit/0e64348ccaf513de731f403259ec5b49e7b3f028 changed job['wrapped'] to contain a class instead of the class name as a string, causing these types of errors whenever a trace contains a Sidekiq job.

```ERROR -- ddtrace: [ddtrace] (/usr/local/bundle/gems/ddtrace-0.32.0/lib/ddtrace/transport/http/client.rb:46:in `rescue in send_request') Internal error during HTTP transport request. Cause: undefined method `to_msgpack' for Searchkick::ReindexV2Job:Class Location: /usr/local/bundle/gems/msgpack-1.3.1/lib/msgpack.rb:46:in `write'```

**Comment by delner** [comment] 2020-02-07 15:57
Ah okay, this makes sense, we'll get a bugfix out for this. Thanks @pj0tr!

**Comment by delner** [comment] 2020-02-13 19:55
Opened a PR for this, but not sure if it fixes the problems since I've been unable to reproduce it. Can you try and verify this @pj0tr ?

**Comment by MattRMcFarland** [comment] 2020-02-24 23:06
+1 We're also running into the same issue. @pj0tr I'd be happy to help reproduce. I'm not quite sure how to build the gem at this sha and use it in my local environment though. Any guidance there?

**Comment by delner** [comment] 2020-02-25 17:12
@mattmcf You have two options to use the current PR #947:

1. Use the branch directly `gem 'ddtrace', git: 'https://github.com/DataDog/dd-trace-rb, branch 'fix/sidekiq_with_rails_6.0.2'`
2. Use the preview build (okay for temporary use but not long term):

```ruby
source 'http://gems.datadoghq.com/prerelease' do
  gem 'ddtrace', '0.32.0.fix.sidekiq.with.rails.6.0.2.56001'
end
```

**Comment by mattmcf** [comment] 2020-02-25 21:59
@delner Thanks! That worked great.

I can confirm that this fix addressed the issue for me. I'm now seeing spans emitted when I wasn't before.

**Comment by delner** [comment] 2020-02-25 23:41
Okay, wonderful, thanks for the confirmation @mattmcf! We'll get this merged and released.

**Closed** 2020-02-26 17:22 UTC
Labels: bug, community, integrations

**Comment by mattmcf** [comment] 2020-02-27 17:35
@delner Do you know when you'll cut the release?

**Comment by delner** [comment] 2020-02-28 02:56
Likely next week.
