### ISSUE TITLE
Nested tracing not working

### ISSUE THREAD

**Issue by juanibiapina** [DataDog/dd-trace-rb#492] opened 2018-07-17 10:30 UTC
We've recently updated to version 0.13.0 (from 0.7.2). After the update, we're losing traces. We use the rails integration, but we've been able to reproduce in the rails console like this:

In this case we get only the `outer` trace:

```ruby
Datadog.tracer.trace("outer") do |span|
  Datadog.tracer.trace("inner") do |span|
    sleep 1
  end
end
```

In this case we get no traces at all:

```ruby
Datadog.tracer.trace("outer") do |span|
  Datadog.tracer.trace("inner") do |span|
    span.parent = nil
    sleep 1
  end
end
```

We're still investigating further.

**Comment by delner** [comment] 2018-07-17 13:51
Thanks for the report @juanibiapina . Can you try activating debug mode on the tracer configuration and let me know what it prints for the top example?

Here's my output running in a Rails app using the latest `ddtrace` (0.13.0) from master (which looks correct):

```
$ bundle exec rails c
Loading development environment (Rails 5.1.4)
2.4.2 :001 > Datadog.tracer.trace("outer") do |span|
2.4.2 :002 >       Datadog.tracer.trace("inner") do |span|
2.4.2 :003 >           sleep 1
2.4.2 :004?>       end
2.4.2 :005?>   end
D, [2018-07-17T09:47:05.499643 #44411] DEBUG -- ddtrace: [ddtrace] (/dd-trace-rb/lib/ddtrace/tracer.rb:343:in `write') Writing 2 spans (enabled: true)
D, [2018-07-17T09:47:05.500615 #44411] DEBUG -- ddtrace: [ddtrace] (/dd-trace-rb/lib/ddtrace/tracer.rb:346:in `write') [
 Name: outer
Span ID: 2385497841090987679
Parent ID: 0
Trace ID: 1127867115924865366
Type:
Service: dd_rails_test
Resource: outer
Error: 0
Start: 1531835224496432896
End: 1531835225499323904
Duration: 1002891000
Tags: [
   system.pid => 44411]
Metrics: [ ],

 Name: inner
Span ID: 8632218364709652360
Parent ID: 2385497841090987679
Trace ID: 1127867115924865366
Type:
Service: dd_rails_test
Resource: inner
Error: 0
Start: 1531835224496644096
End: 1531835225499228928
Duration: 1002585000
Tags: [
   ]
Metrics: [ ]]

D, [2018-07-17T09:47:05.501002 #44411] DEBUG -- ddtrace: [ddtrace] (/dd-trace-rb/lib/ddtrace/workers.rb:70:in `block in start') Starting thread in the process: 44411
D, [2018-07-17T09:47:05.501777 #44411] DEBUG -- ddtrace: [ddtrace] (/dd-trace-rb/lib/ddtrace/transport.rb:103:in `post') Sending data from process: 44411
 => 1
2.4.2 :006 > D, [2018-07-17T09:47:05.507848 #44411] DEBUG -- ddtrace: [ddtrace] (/dd-trace-rb/lib/ddtrace/transport.rb:172:in `handle_response') Payload correctly sent to the trace agent.
D, [2018-07-17T09:47:05.508060 #44411] DEBUG -- ddtrace: [ddtrace] (/dd-trace-rb/lib/ddtrace/transport.rb:103:in `post') Sending data from process: 44411
D, [2018-07-17T09:47:05.510714 #44411] DEBUG -- ddtrace: [ddtrace] (/dd-trace-rb/lib/ddtrace/transport.rb:172:in `handle_response') Payload correctly sent to the trace agent.
```

**Comment by juanibiapina** [comment] 2018-07-17 14:16
For the first case, the same one you tested, I get the same output you do. The payload is sent to the agent twice, one for each block. In datadog, I still only see the outer one.

For the second case I get an error:

```
D, [2018 ... ruby/2.2.0/gems/ddtrace-0.13.0/lib/ddtrace/context.rb:98:in `block in close
_span') root span inner closed but has 1 unfinished spans:
D, [2018 ... ruby/2.2.0/gems/ddtrace-0.13.0/lib/ddtrace/context.rb:100:in `block (2 leve
ls) in close_span') unfinished span: Span(name:outer,sid:5866296000397793914,tid:6281358271855332459,pid:0)
```

**Comment by delner** [comment] 2018-07-17 14:49
Here's a screenshot from the Datadog UI from example 1, which seems to be working:

![screen shot 2018-07-17 at 10 33 55 am](https://user-images.githubusercontent.com/3237131/42824129-2f3d1a6c-89ad-11e8-9824-9a7c1e0e2693.png)

The second case error is definitely not good. You're receiving this error because despite clearing the parent, both spans are bound to the same context, so when the child finishes and it looks like a "root span" (e.g. no parent), the tracer checks for then discards any unfinished spans, in this case `outer`, in the same context (as a safety precaution.)

I don't think you can clear the parent like that without causing side effects. Is there a reason for doing so? If you need to do something like this, you could try doing:

```ruby
Datadog.tracer.trace("outer") do |span|
  begin
    child = Datadog.tracer.start_span("inner", child_of: nil)
    sleep 1
  ensure
    child.finish
  end
end
```

This will produce `outer` and `inner` as separate traces, because they will each end up in their own contexts. The `child_of` option on `start_span` allows you to override context. There aren't many cases where I think you'd want to do this (maybe except for some multi-threading scenario?).

**Comment by juanibiapina** [comment] 2018-07-17 15:10
The second case is mostly legacy I think. I'll remove it since I don't really need it.

We'll continue investigating on our side why we don't see the metrics on datadog UI.

**Comment by delner** [comment] 2018-07-17 15:26
@juanibiapina My next suggestion would be to look at the trace agent logs. It should be possible to check those to see if there's something strange going on.

**Comment by delner** [comment] 2018-07-17 15:37
It can be used, but not in this way. It's a fairly low-level function over which context management (e.g. auto-parenting spans) is layered upon, such that if you change a span that's being automatically managed, it can cause unexpected behavior.

If you opt to not use automatic context management and prefer to manage all of the parenting relationships manually, you can do that using `start_span` as linked above, in which case `parent=` would be safe to use.

**Comment by juanibiapina** [comment] 2018-07-17 16:12
Yep, I can see that.

We'll continue to investigate the first case, which seems to be the correct one and should work.

**Comment by juanibiapina** [comment] 2018-07-17 16:19
Ok, in summary:

This works:
```ruby
Datadog.tracer.trace("outer") do |span|
  begin
    child = Datadog.tracer.start_span("inner", child_of: nil)
    sleep 1
  ensure
    child.finish
  end
end
```

But this fails to send the inner trace:
```ruby
Datadog.tracer.trace("outer") do |span|
  Datadog.tracer.trace("inner") do |span|
    sleep 1
  end
end
```

**Comment by delner** [comment] 2018-07-17 16:45
Can you share a screenshot of UI for the trace, from the lower example?

**Comment by juanibiapina** [comment] 2018-07-17 16:47
![screen shot 2018-07-17 at 18 47 07](https://user-images.githubusercontent.com/568764/42832569-e1bf6fe8-89f1-11e8-9f7e-a0a881a40ac4.png)
![screen shot 2018-07-17 at 18 47 23](https://user-images.githubusercontent.com/568764/42832570-e1e198ca-89f1-11e8-84ca-2055bda785e4.png)

**Comment by delner** [comment] 2018-07-17 16:51
What page is this from? My previous screenshot came from the Services page in APM (a URL like `https://app.datadoghq.com/apm/service/dd_rails_test/outer`.)

**Comment by juanibiapina** [comment] 2018-07-17 16:57
That's from the metrics summary page. From the services page:

outer4
![screen shot 2018-07-17 at 18 56 34](https://user-images.githubusercontent.com/568764/42832978-391c7794-89f3-11e8-88de-8c47fe3602c6.png)

inner4
![screen shot 2018-07-17 at 18 56 53](https://user-images.githubusercontent.com/568764/42832979-39388e66-89f3-11e8-81f5-e15be475fa04.png)

**Comment by delner** [comment] 2018-07-17 17:03
And what URL did you get the lower screen shot from? And where did you find that URL from?

**Comment by juanibiapina** [comment] 2018-07-17 17:11
I replaced the metric name in the URL because I couldn't find a link to that page.

Is there a point to your investigation that I can try to check on my side?

**Comment by delner** [comment] 2018-07-17 17:20
If I'm understanding the circumstances and your intent correctly, I don't think you should expect to see `inner` as a metric. Spans that are children to other root spans in the same service do not have metrics calculated on them that are directly visible or discrete from their parent. Rather, the root span of a service has metrics calculated for it.

This is probably why you don't see this visible in the UI. However, the `inner` span is likely being correctly recorded and processed, which is something you could verify by opening the trace with `outer` on it, then seeing if `inner` appears within its flame graph.

I will double check with our team about the expected behavior here, but I think that's how its working.

**Comment by juanibiapina** [comment] 2018-07-17 17:31
I don't see this flame anywhere, but I see your point.

My interpretation is that the original intent of the `set_parent(nil)` call on our code was to have these two as separate metrics. This used to work on 0.7.0 (probably), but now explodes on 0.13.2, which causes both metrics not to be sent.

The correct solution in this case is to use `start_span`, since we want a separate metric.

Makes sense? You can close this if you want then.

**Comment by delner** [comment] 2018-07-18 17:43
Alright, I'll close this for now, but please feel free to leave any other questions or suggestions here if you need any more help on this.

**Closed by delner** 2018-07-18 17:43 UTC
