### ISSUE TITLE
Rails 6.1 and ActiveRecord multiple database issue

### ISSUE THREAD

**Issue by thibaudgg** [DataDog/dd-trace-rb#1567] opened 2021-06-25 07:21 UTC
Since we upgraded our Rails app to 6.1 all the ActiveRecord tracing are broken, our current config looks like that:

``` ruby
# config/initializers/datadog-tracer.rb
Datadog.configure do |c|
  c.use :rails,
    service_name: 'our-app',
    controller_service: 'rails-controller',
    database_service: 'pg-primary',
    cache_service: 'rails-cache'

  c.use :active_record, describes: :primary, service_name: 'pg-primary'
  c.use :active_record, describes: :follower, service_name: 'pg-follower'

  # ...
end
```

If we comment the `c.use :active_record` definitions then we get the expected tracing for the `db-primary` but as soon we uncomment them we only get the tracing for what I suppose is AR opening PostgreSQL connection commands (`SET ...`, `SHOW TIME ZONE`) and nothing more.

We also tried [different partial `describes:` with the DB hosts](https://github.com/DataDog/dd-trace-rb/blob/0794be4cd455caf32e7a9c8f79d80a4b77c4087a/docs/GettingStarted.md#active-record) but that didn't make any difference.

Something seems broken with Rails 6.1 and multiple databases that prevents the DB requests tracing to be captured. We were previously using `ddtrace` 0.43.0, and upgrading to 0.50.0 doesn't fix this issue. Our app is running on Ruby 2.7.3 and is hosted on Heroku.

Any idea of what is going wrong here? Thanks for your help!

**Comment by ericmustin** [comment] 2021-07-07 05:01
@thibaudgg Hey thanks for the report here. Apologies on the delayed response. I've scheduled some time this week to try to reproduce this. It would be useful though if you could open a ticket with support@datadoghq.com as well  as we'd like to be able to track these sort of potential regressions as well as because I may need to request some debug logs or configuration details that may contain sensitive information. sorry again for delay here

**Comment by thibaudgg** [comment] 2021-07-07 09:11
Thanks for looking at it @ericmustin, I just opened a ticket with support@datadoghq.com with the same title as this issue.

**Comment by thibaudgg** [comment] 2021-08-03 06:43
@ericmustin went back from vacation yesterday and followed up on the support ticket with the requested information.

**Comment by senny** [comment] 2022-05-05 08:43
I believe the issue is still relevant, any updates on how it could be resolved?

**Comment by marcotc** [comment] 2022-05-16 23:57
Hey everyone, I took a look a this issue last Friday, setting up a Rails 6.1 application, but was able to get the
```ruby
  c.use :active_record, describes: :primary, service_name: 'pg-primary'
  c.use :active_record, describes: :follower, service_name: 'pg-follower'
```
to work correctly without any modifications.

We are talking directly internally with a client to help debug this issue using a realistic production setup, so we'll get back here when we have updates.

**Comment by thibaudgg** [comment] 2022-05-30 06:58
Hey @marcotc, as communicated with your support, since we upgraded `ddtrace` to 1.0.0 the multiple AR databases metrics are fixed now. Rails was also upgrade to the latest version (7.0.2.4) in the meantime so I'm not quite sure which upgrades combination fixed our setup.

**Comment by marcotc** [comment] 2022-05-30 21:26
@thibaudgg that's good to hear, sorry it took us so long to get back to you.

@senny, what version of `ddtrace` and `rails` are you running, I'm wondering if an upgraded version of `ddtrace` (1.0.0 or higher) would address this issue for your application.

**Comment by thibaudgg** [comment] 2022-05-31 06:16
@marcotc, @senny and I are working together ;).

**Comment by ivoanjo** [comment] 2022-06-07 08:04
Great! It sounds like the issue is finally solved in the latest `ddtrace`, so I'm going ahead and close this ticket. Let us know if we can provide any more help! 😄🚀

**Closed by ivoanjo** 2022-06-07 08:04 UTC
Labels: community
