### ISSUE TITLE
NoMethodError  undefined method `service=' for nil:NilClass 

### ISSUE THREAD

**Issue by nwj** [DataDog/dd-trace-rb#684] opened 2019-02-04 20:27 UTC
Hi there,

We're getting `NoMethodError  undefined method 'service=' for nil:NilClass` exceptions out of dd-trace in a handful of rare cases that we're not totally able to reproduce. Our application depends on redis, and we think the times that this has raised coincide with points when we've lost a redis node.

Relevant stack trace from our logs below:
```
NoMethodError: undefined method `service=' for nil:NilClass
  from ddtrace/contrib/redis/patcher.rb:65:in `block in call'
  from ddtrace/tracer.rb:296:in `ensure in trace'
  from ddtrace/tracer.rb:296:in `trace'
  from ddtrace/contrib/redis/patcher.rb:64:in `call'
  from redis.rb:2123:in `block in hgetall'
  from redis.rb:58:in `block in synchronize'
```

Our non-expert opinion is that adding a nil check to `ddtrace/contrib/redis/patcher.rb` might be no regrets and would harden the gem against this (admittedly, somewhat sketchy) edge-case. But happy to engage with you further on it if there's additional information we can provide that might help.

**Comment by delner** [comment] 2019-02-05 16:10
Thanks for the report @nwj!

So the line in question is a bit crazy (https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/redis/patcher.rb#L65), since it seems to suggest that `tracer.trace` is not returning a span.

Digging deeper, only way I can see this happen is when this line (https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/tracer.rb#L301) catches an error, and a span isn't created. So it looks like `start_span` might be throwing an error in your edge case; question is, what is failing?

This is unlikely, but you don't have any associated `Failed to start span` messages in your log around this same time, do you? It would only appear if debug mode were enabled. If not, I wouldn't recommend enabling debug in a production environment (since its very noisy), but if you're able to replicate this is a dev/staging/test environment, maybe enabling that debug flag there instead will surface the error in question. If it can't be reproduced outside production, I might suggest temporarily deploying a fork that elevates just this error message from "debug" to "error" or higher, so it's captured.

**Comment by nwj** [comment] 2019-02-08 01:03
Thanks for the response @delner 

Checked our logs and we don't see any `Failed to start span`, but that's also expected as we don't run in production in debug mode.

We could try running with a fork that escalates that one message, but it's not top priority for us right now given that we've only seen this occur a handful of times in our logs.

**Comment by delner** [comment] 2019-04-25 16:47
Hey @nwj Is this still an issue? We've done a few releases since this was opened, and I might recommend trying those (though I can't say confidently it will resolve the issue.) I'm going to close this for now, but if you try the newest version, find the issue still exists and generate some diagnostics for it, then feel free to re-open and we'll take a fresh look at it.

**Closed by delner** 2019-04-25 16:47 UTC
Labels: bug, community, core
