### ISSUE TITLE
Large memory increase after upgrading to 0.12.0

### ISSUE THREAD

**Issue by senny** [DataDog/dd-trace-rb#431] opened 2018-05-23 11:51 UTC
We have just upgraded to `0.12.0`. As we are using `c.use :rails` this would enable allocation tracing for our deployment. Shortly after deploying to production we have observed a large increase in the memory footprint of our processes. Some samples from our monitoring:

![screen shot 2018-05-23 at 13 38 16](https://user-images.githubusercontent.com/5402/40422150-ab5b304c-5e8e-11e8-9884-b90932968b5d.png)

![screen shot 2018-05-23 at 13 38 42](https://user-images.githubusercontent.com/5402/40422157-af4caa00-5e8e-11e8-997d-369cc0d05e8f.png)

![screen shot 2018-05-23 at 13 40 08](https://user-images.githubusercontent.com/5402/40422196-d6945900-5e8e-11e8-9cf7-53cf270e7b4a.png)

I have not found an option in the `use :rails` configuration to disable instantiation tracing, so it's hard to say if this feature is where the issue comes from. We have since reverted the gem upgrade to return to our usual memory consumption.

**Comment by delner** [comment] 2018-05-23 14:15
@senny Thanks for the report! Instantiation tracing is probably the biggest change to Rails in the most recent release, so I think that's a reasonably good place to begin our investigation into this.

If we were to open a pull request that adds a flag to optionally enable/disable instantiation tracing for Rails, would you be able to use it to verify whether in fact it is isolated to that feature?

**Comment by senny** [comment] 2018-05-23 14:47
> If we were to open a pull request that adds a flag to optionally enable/disable instantiation tracing for Rails, would you be able to use it to verify whether in fact it is isolated to that feature?

I think I would be open to deploy a version with this disabled.

On the note of adding flags, it would be nice to have one to override the default `orm_service_name` of `active_record` as well 😅.

**Comment by delner** [comment] 2018-05-23 15:31
@senny Oh, right, I don't think you can do that from `:rails` directly. You can override it though, by adding a `use :active_record` and adding the `orm_service_name` option there. You typically shouldn't see it fallback to `active_record` unless the instantiation span has no parent (usually it'll inherit and append itself to the parent service.)

**Comment by delner** [comment] 2018-05-23 16:42
We've seen this most commonly come from Rake tasks, scripts, and asynchronous tasks. Typically we advise that these "entry points" be identified and wrapped with some kind of meaningful parent span. We cover several common examples of this with Resque, Sidekiq, Racecar, and now in `0.13-dev`, Rake as well.

**Comment by senny** [comment] 2018-05-24 12:21
> We've seen this most commonly come from Rake tasks, scripts, and asynchronous tasks that run within a Rails environment setting (which typically instruments codes under all code paths, interesting to trace or not.)

Right, we do have a couple threads that run general application loops. I'll look into wrapping them with a span.

**Comment by pawelchcki** [comment] 2018-05-25 15:06
Thanks again for reporting it @senny

I've created a branch https://github.com/DataDog/dd-trace-rb/pull/435. Where one can control `active_record` instrumentation.
e.g.

```ruby
c.use :active_record, trace_events: [:sql]
```
will disable instantiation tracing. 
and 
```ruby
c.use :active_record, trace_events: [:instantiation]
```
will disable sql tracing.

**Comment by senny** [comment] 2018-05-25 15:08
@pawelchcki thanks, I'll report back when I was able to give it a go in production. Just to confirm. I can use `c.rails` and `c.use :active_record, trace_events: [:sql]` and it does not add the instrumentation twice?

**Comment by pawelchcki** [comment] 2018-05-25 15:21
@senny no it will only run the code once.

**Comment by delner** [comment] 2018-05-31 18:10
@senny Did this help your problem at all?

**Comment by pawelchcki** [comment] 2018-06-05 13:11
@senny Sorry for that - we're actively working on that branch to merge the changes to master. I won't do any more history rewrites so if you still want to test this branch then it should be safe now to use it. 

Or you can wait for it to land in master which should happen in near future. 

https://github.com/DataDog/dd-trace-rb/pull/435

**Comment by senny** [comment] 2018-06-06 13:37
@delner I would have liked to rely on `master` instead of a branch. If it won't be merged without my confirmation I can maybe schedule something later this week or early next week.

I can't give you much details. We are running on Heroku. Only thing we noticed is that our dynos (processes) would hit memory limits soon after the deployments (as shared in the charts). I put our configuration in [this Gist](https://gist.github.com/senny/45e2b30e994e6cd2473fff0eedbd9c47). I don't think I have anything else to share at this point.

**Comment by delner** [comment] 2018-06-06 16:02
Okay. Probably doesn't have anything to do with this but the following options for Rails are deprecated and have no effect:

```ruby
enabled: true
auto_instrument: true
auto_instrument_redis: true
```

**Comment by senny** [comment] 2018-06-06 16:12
> Okay. Probably doesn't have anything to do with this but the following options for Rails are deprecated and have no effect.

Thanks 😅. Will remove them.

**Comment by delner** [comment] 2018-06-15 20:13
We released some improvements to memory usage in #446 as a part of the 0.12.1 release. Feel free to try that out and see if that helps. Going to close this issue for now, however, if memory is still a problem, we'll be happy to revisit it and discuss further steps.

**Comment by senny** [comment] 2018-06-20 09:30
I just deployed 0.12.1 to our staging system. While the difference is not of the same scale, it still looks like there is some significantly larger memory consumption than pre 0.12:

![screen_shot_2018-06-20_at_11_26_50](https://user-images.githubusercontent.com/5402/41650008-4c28c990-747d-11e8-9ac6-bc094554653c.png)

Our staging system has barely any traffic. I'm hesitant to put this into production where the load is a lot higher.

**Comment by delner** [comment] 2018-06-20 15:13
@senny Prior to where the blue arrow is pointing, is that 0.11.4?

We did add quite a bit of new instrumentation in 0.12.0, so I think some increase of memory is to be expected, but I'm always for doing whatever we can to minimize the footprint. (We have a couple of additional minor optimizations to add, but they probably won't make a significant impact on what you're seeing above.)

I think I'm going to need to ask for a little more help debugging this from your side: is there any more detail or info that helps us narrow down the field of possibilities to just the biggest contributors? Perhaps disabling integrations one by one vs a control? Or some other deeper dive?

I'd love to take a huge bite out of this, but at this point I think we need more leads if we're going to be effective in doing so.

**Comment by senny** [comment] 2018-06-21 13:55
Before the marker is `0.11.3`.

> We did add quite a bit of new instrumentation in 0.12.0, so I think some increase of memory is to be expected, but I'm always for doing whatever we can to minimize the footprint.

But isn't this a bit worrying? The memory increase after just upgrading to `0.12.1` was 23%. That's pretty crazy. We also did not change our configuration meaning that we have not enabled more integrations (except Active Record instantiation tracking that adds ontop of an extension we already have enabled).

In the deployments that you are running, do you not observe a similar memory consumption increase when switching from 0.11 to 0.12?

> Is there any more detail or info that helps us narrow down the field of possibilities to just the biggest contributors? Perhaps disabling integrations one by one vs a control? Or some other deeper dive?

I don't think I have anything else that I can share. Current project timelines do not allow me to dig deeper into this issue right now. I know this is not very helpful but considering the situation we are pretty much locked into using `0.11`.

**Comment by senny** [comment] 2018-06-21 13:57
One more question, with `0.12.1` it is not possible just to disable AR instantiation tracking, correct?

**Comment by delner** [comment] 2018-06-21 18:19
@senny It is a bit worrying, and we are treating this seriously. My comment was only to suggest that once any memory issues we find are addressed, there still might be some increase between versions if that increase is found to be necessary to support a new feature. It's just important to make sure any such increase is actually reasonable, and not inadvertent. And thus far, there still haven't been any such conclusions drawn.

We have spent considerable time attempting to reproduce memory issues in our sample applications by doing comparative analysis, and thus far have not been able to reliably recreate this issue, given the parameters that have been described previously. Most of the larger, more obvious issues that were discovered as a part of this investigation were addressed in 0.12.1, but acknowledge that there are likely still some improvements to be made to bring things closer to a 0.11.4 level.

That said, I think one of our findings was that instantiation tracing had little impact on memory consumption, but that memory consumption may correlate with caching. Can you tell me more about your use of any caching instrumentation? Does your application use Rails caching? Do you instrument it? Can you describe me some properties about your use of caching? How large is your cache? How many keys are present? What are the length of the keys?

We'll keep digging into this as long as there are leads to investigate, or until the issue is satisfactorily resolved.

**Comment by senny** [comment] 2018-06-22 06:47
Thanks for the in depth reply. We are using the `dalli` extension as well as `redis`. The application does make use of `Rails.cache` but the caches are nothing huge. Also, redis is mainly backing Sidekiq and in another case some transient data that we keep for roughly 2 hours. Redis receives a lot of traffic while memcache is pretty low profile. 

In terms of cache size, Memcache is only around 100MB while Redis is 500MB.

Note that we had these extensions enabled before the upgrade as well. I would be ok to deploy to production without memcache instrumentation. `redis` is a bit of a different story, we rely heavily on the metrics for Sidekiq and Redis.

**Comment by delner** [comment] 2018-06-22 15:05
If I'm remembering correctly, I think the suspected caching issues largely stemmed from Rails caching, not any direct use of Redis or Dalli (that I'm aware of.)

You mentioned this is even an issue in your staging environment: if we issued another PR, with some more potential optimizations (including those that might address caching), would you be able to test it there and give us some feedback as to its effectiveness?

**Comment by senny** [comment] 2018-06-22 15:10
> You mentioned this is even an issue in your staging environment

Yes.

> would you be able to test it there and give us some feedback as to its effectiveness?

Yes.

The first graphs in the issue description were from production. The memory increase there was huge (Note that this was 0.12.0 though). I have only tested `0.12.1` in staging. What's noteworthy is that the increase in memory kicks in relatively fast. It's as if the process baseline was just increased by ~23%. It's hard to imagine that this stems from any kind of instrumentation volume (our staging platform is not that busy). It's also interesting that the increase kicks in very quickly after the restart. Are there updated dependencies involved? Or any other large object buildups that would happen while a process is booting?

**Comment by delner** [comment] 2018-06-22 15:37
> What's noteworthy is that the increase in memory kicks in relatively fast. It's as if the process baseline was just increased by ~23%. It's hard to imagine that this stems from any kind of instrumentation volume (our staging platform is not that busy).

Yeah, this is what bugs me a bit, too. It's unclear to me right now what part of tracer would correlate more with so baseline than usage. Most of what allocates memory is based off application activity: when integration functions run and it creates spans to match. At this point I can't think of anything that would collect large quantities of objects at startup. Some dependencies have been updated I'm sure (since we introduced new integrations), but I'm not yet sure how those would factor in.

Nonetheless, this does warrant further study. Thanks for your patience and consistent feedback with this so far; we really appreciate it! We'll draft another PR that will introduce some more possible optimizations, and check back with you then.

**Comment by senny** [comment] 2018-06-22 15:45
@delner I'm happy to provide feedback whenever possible. Thanks for helping me out on this. Your work is very much appreciated.

**Comment by delner** [comment] 2018-06-28 18:08
@senny Your most recent graph, showing 0.12.1. What process is this? Is this a sidekiq process or is it a Rails web server process?

**Comment by senny** [comment] 2018-06-29 08:51
@delner I'm pretty sure it was a Sidekiq worker.

**Comment by delner** [comment] 2018-06-29 20:02
@senny Cool, were the original graphs at the top also Sidekiq workers? (I assume so because I see `worker` in the name, but just want to be sure.)

**Comment by senny** [comment] 2018-07-01 08:34
@delner correct. It's even a couple of Sidekiq workers that will fork.

**Comment by pawelchcki** [comment] 2018-07-04 16:03
@senny Just to let you know - we are actively working on this issue and we've made it our top priority for next release. Right now we are benchmarking our code to find possible memory optimizations.

**Comment by senny** [comment] 2018-07-04 16:10
@pawelchcki thanks for the update and the good news. Let me know when I can provide some inputs or run something in our staging environment.

**Comment by pawelchcki** [comment] 2018-07-09 15:01
@senny We've created PR #477 that addresses an issue with unclosed spans causing memory use increase. Its possible you've been affected by it as it specifically shows up in multithreaded applications, you should be able to verify that by running that PR on staging.

**Comment by senny** [comment] 2018-07-18 16:01
Thanks for all the work. We are currently running the latest version `0.13.1` and the memory stays fairly consistent with previous version.

**Comment by pawelchcki** [comment] 2018-07-18 17:10
Thank you for helping us diagnose it and thanks for the update @senny. If you feel the issue has been resolved, feel free to close it.

**Closed** 2018-07-30 09:13 UTC
Labels: bug, community, integrations
