### ISSUE TITLE
Instrumentation of Rails app fails on jRuby: RuntimeError: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by h4l** [DataDog/dd-trace-rb#3258] opened 2023-11-15 12:47 UTC
**Current behaviour**

ddtrace triggers `RuntimeError: can't add a new key into hash during iteration` during startup of a Rails app running on jRuby (9.2.21.0).

It doesn't occur consistently, but perhaps 50% of the time. This seems to have started between ddtrace 1.6.0 and 1.6.2 (I've not seen this happen in 1.5.0).

**Expected behaviour**
Should not trigger the error.

**Steps to reproduce**
I don't have a simple repo right now. This is occurring in quite a complex app which I'm containerising for deployment and didn't develop myself.

This is the traceback:

```
RuntimeError: can't add a new key into hash during iteration
                                     []= at org/jruby/RubyHash.java:1055
                              instrument at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/extensions.rb:162
                          activate_rack! at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/framework.rb:61
                                   setup at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/framework.rb:47
                               configure at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/core/configuration.rb:82
                               configure at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/extensions.rb:64
                                   setup at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/framework.rb:37
                            setup_tracer at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/patcher.rb:81
                        after_initialize at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/patcher.rb:75
                                     run at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/core/utils/only_once.rb:26
                             synchronize at org/jruby/ext/thread/Mutex.java:164
                                     run at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/core/utils/only_once.rb:21
                        after_initialize at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/patcher.rb:72
                  patch_after_initialize at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/patcher.rb:67
                           instance_eval at org/jruby/RubyBasicObject.java:2632
                            execute_hook at /opt/archivesspace/gems/gems/activesupport-5.2.8.1/lib/active_support/lazy_load_hooks.rb:71
                  with_execution_control at /opt/archivesspace/gems/gems/activesupport-5.2.8.1/lib/active_support/lazy_load_hooks.rb:62
                            execute_hook at /opt/archivesspace/gems/gems/activesupport-5.2.8.1/lib/active_support/lazy_load_hooks.rb:67
                          run_load_hooks at /opt/archivesspace/gems/gems/activesupport-5.2.8.1/lib/active_support/lazy_load_hooks.rb:52
                                    each at org/jruby/RubyArray.java:1821
                          run_load_hooks at /opt/archivesspace/gems/gems/activesupport-5.2.8.1/lib/active_support/lazy_load_hooks.rb:51
                                Finisher at /opt/archivesspace/gems/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:75
                           instance_exec at org/jruby/RubyBasicObject.java:2704
                                     run at /opt/archivesspace/gems/gems/railties-5.2.8.1/lib/rails/initializable.rb:32
                        run_initializers at /opt/archivesspace/gems/gems/railties-5.2.8.1/lib/rails/initializable.rb:61
                              tsort_each at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:228
       each_strongly_connected_component at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:350
  each_strongly_connected_component_from at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:431
       each_strongly_connected_component at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:349
                                    each at org/jruby/RubyArray.java:1821
                                    call at org/jruby/RubyMethod.java:131
       each_strongly_connected_component at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:347
                              tsort_each at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:226
                              tsort_each at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:205
                        run_initializers at /opt/archivesspace/gems/gems/railties-5.2.8.1/lib/rails/initializable.rb:60
                             initialize! at /opt/archivesspace/gems/gems/railties-5.2.8.1/lib/rails/application.rb:361
                                  <main> at /var/tmp/archivesspace/jetty-0_0_0_0-8081-public_war-_-any-18010865208611397353/webapp/WEB-INF/config/environment.rb:5
                                 require at org/jruby/RubyKernel.java:974
                        load_environment at uri:classloader:/jruby/rack/rails/environment3.rb:25
                        load_environment at uri:classloader:/jruby/rack/rails_booter.rb:83
                                  <main> at <script>:1
                            start_server at launcher/launcher.rb:90
                                    main at launcher/launcher.rb:154
                                  <main> at launcher/launcher.rb:242
```

<details>
<summary>More log output</summary>

```
Nov 15, 2023 10:53:53 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
INFO: An exception happened during JRuby-Rack startup
can't add a new key into hash during iteration
--- System
jruby 9.2.21.0 (2.5.8) 2022-06-27 49e5080a7c OpenJDK 64-Bit Server VM 17.0.9+9 on 17.0.9+9 +jit [linux-x86_64]
Time: 2023-11-15 10:53:53 +0000
Server: jetty/9.4.44.v20210927
jruby.home: uri:classloader://META-INF/jruby.home

--- Context Init Parameters:
jruby.max.runtimes = 1
jruby.min.runtimes = 1
jruby.rack.error = false
public.root = /
rails.env = production

--- Backtrace
RuntimeError: can't add a new key into hash during iteration
                                     []= at org/jruby/RubyHash.java:1055
                              instrument at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/extensions.rb:162
                          activate_rack! at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/framework.rb:61
                                   setup at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/framework.rb:47
                               configure at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/core/configuration.rb:82
                               configure at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/extensions.rb:64
                                   setup at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/framework.rb:37
                            setup_tracer at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/patcher.rb:81
                        after_initialize at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/patcher.rb:75
                                     run at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/core/utils/only_once.rb:26
                             synchronize at org/jruby/ext/thread/Mutex.java:164
                                     run at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/core/utils/only_once.rb:21
                        after_initialize at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/patcher.rb:72
                  patch_after_initialize at /opt/archivesspace/plugins/aspace_datadog/gems/gems/ddtrace-1.16.2/lib/datadog/tracing/contrib/rails/patcher.rb:67
                           instance_eval at org/jruby/RubyBasicObject.java:2632
                            execute_hook at /opt/archivesspace/gems/gems/activesupport-5.2.8.1/lib/active_support/lazy_load_hooks.rb:71
                  with_execution_control at /opt/archivesspace/gems/gems/activesupport-5.2.8.1/lib/active_support/lazy_load_hooks.rb:62
                            execute_hook at /opt/archivesspace/gems/gems/activesupport-5.2.8.1/lib/active_support/lazy_load_hooks.rb:67
                          run_load_hooks at /opt/archivesspace/gems/gems/activesupport-5.2.8.1/lib/active_support/lazy_load_hooks.rb:52
                                    each at org/jruby/RubyArray.java:1821
                          run_load_hooks at /opt/archivesspace/gems/gems/activesupport-5.2.8.1/lib/active_support/lazy_load_hooks.rb:51
                                Finisher at /opt/archivesspace/gems/gems/railties-5.2.8.1/lib/rails/application/finisher.rb:75
                           instance_exec at org/jruby/RubyBasicObject.java:2704
                                     run at /opt/archivesspace/gems/gems/railties-5.2.8.1/lib/rails/initializable.rb:32
                        run_initializers at /opt/archivesspace/gems/gems/railties-5.2.8.1/lib/rails/initializable.rb:61
                              tsort_each at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:228
       each_strongly_connected_component at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:350
  each_strongly_connected_component_from at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:431
       each_strongly_connected_component at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:349
                                    each at org/jruby/RubyArray.java:1821
                                    call at org/jruby/RubyMethod.java:131
       each_strongly_connected_component at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:347
                              tsort_each at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:226
                              tsort_each at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:205
                        run_initializers at /opt/archivesspace/gems/gems/railties-5.2.8.1/lib/rails/initializable.rb:60
                             initialize! at /opt/archivesspace/gems/gems/railties-5.2.8.1/lib/rails/application.rb:361
                                  <main> at /var/tmp/archivesspace/jetty-0_0_0_0-8081-public_war-_-any-18010865208611397353/webapp/WEB-INF/config/environment.rb:5
                                 require at org/jruby/RubyKernel.java:974
                        load_environment at uri:classloader:/jruby/rack/rails/environment3.rb:25
                        load_environment at uri:classloader:/jruby/rack/rails_booter.rb:83
                                  <main> at <script>:1
                            start_server at launcher/launcher.rb:90
                                    main at launcher/launcher.rb:154
                                  <main> at launcher/launcher.rb:242

--- RubyGems
Gem.dir: /opt/archivesspace/gems
Gem.path:
/root/.gem/jruby/2.5.0
uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared
/opt/archivesspace/gems
Activated gems:
  did_you_mean-1.2.1
  fileutils-1.1.0
  bundler-2.1.4
  rake-13.0.6
  concurrent-ruby-1.2.2
  i18n-0.9.5
  minitest-5.15.0
  thread_safe-0.3.6-java
  tzinfo-1.2.11
  activesupport-5.2.8.1
  builder-3.2.4
  erubi-1.12.0
  racc-1.6.2-java
  nokogiri-1.12.5-java
  rails-dom-testing-2.0.3
  crass-1.0.6
  loofah-2.19.1
  rails-html-sanitizer-1.5.0
  actionview-5.2.8.1
  rack-2.2.6.2
  rack-test-2.0.2
  actionpack-5.2.8.1
  nio4r-2.5.8-java
  websocket-extensions-0.1.5
  websocket-driver-0.7.5-java
  actioncable-5.2.8.1
  globalid-1.1.0
  activejob-5.2.8.1
  mini_mime-1.1.2
  digest-3.1.1-java
  io-wait-0.3.0-java
  timeout-0.3.2
  net-protocol-0.1.2
  strscan-3.0.6-java
  net-imap-0.2.2
  net-pop-0.1.2
  net-smtp-0.3.0
  mail-2.8.1
  actionmailer-5.2.8.1
  activemodel-5.2.8.1
  arel-9.0.0
  activerecord-5.2.8.1
  marcel-1.0.2
  activestorage-5.2.8.1
  atomic-1.0.1-java
  execjs-2.8.1
  autoprefixer-rails-10.4.13.0
  rb-fsevent-0.11.2
  ffi-1.15.5-java
  rb-inotify-0.10.1
  sass-listen-4.0.0
  sass-3.7.4
  bootstrap-sass-3.3.7
  clipboard-rails-1.7.1
  coffee-script-source-1.12.2
  coffee-script-2.4.1
  method_source-1.0.0
  thor-1.2.1
  railties-5.2.8.1
  coffee-rails-4.2.2
  connection_pool-2.3.0
  msgpack-1.7.2-java
  datadog-ci-0.3.0
  debase-ruby_core_source-3.2.2
  libdatadog-5.0.0.1.0
  libddwaf-1.14.0.0.0-java
  ddtrace-1.16.2
  excon-0.99.0
  font-awesome-sass-4.7.0
  htmlentities-4.3.4
  jquery-rails-4.5.1
  json-2.6.3-java
  json-schema-1.0.10
  multipart-post-1.2.0
  net-http-persistent-4.0.1
  sprockets-3.7.2
  sprockets-rails-2.3.3
  rails-5.2.8.1
  tilt-2.1.0
  sass-rails-5.1.0
  therubyrhino_jar-1.7.8
  therubyrhino-2.1.2
  turbolinks-source-5.2.0
  turbolinks-5.2.1
  tzinfo-data-1.2022.7
  uglifier-4.2.0

--- Bundler
Bundler.bundle_path: /opt/archivesspace/gems
Bundler.root: /var/tmp/archivesspace/jetty-0_0_0_0-8081-public_war-_-any-18010865208611397353/webapp/WEB-INF
Gemfile: /var/tmp/archivesspace/jetty-0_0_0_0-8081-public_war-_-any-18010865208611397353/webapp/WEB-INF/Gemfile
Settings:
  jobs = 8
  without = [:test, :development, :doc]
  gemfile = /var/tmp/archivesspace/jetty-0_0_0_0-8081-public_war-_-any-18010865208611397353/webapp/WEB-INF/Gemfile
  bin_path = /opt/archivesspace/gems/gems/bundler-2.1.4/exe/bundle

--- JRuby-Rack Config
compat_version = 
default_logger = org.jruby.rack.logging.StandardOutLogger@4ddaf7c4
equals = <error: >
err = java.io.PrintStream@5783b7d2
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_memory_buffer_size = 
initial_runtimes = 1
jms_connection_factory = 
jms_jndi_properties = 
logger = org.jruby.rack.logging.ServletContextLogger@5cd08a92
logger_class_name = servlet_context
logger_name = jruby.rack
maximum_memory_buffer_size = 
maximum_runtimes = 1
num_initializer_threads = 
out = java.io.PrintStream@79bd5e1b
rackup = 
rackup_path = 
rewindable = true
runtime_arguments = 
runtime_environment = 
runtime_timeout_seconds = 
serial_initialization = false
servlet_context = ServletContext@o.e.j.w.WebAppContext@1e7b3952{/,file:///var/tmp/archivesspace/jetty-0_0_0_0-8081-public_war-_-any-18010865208611397353/webapp/,STARTING}{/opt/archivesspace/wars/public.war}
throw_init_exception = true

```

</details>

**How does `ddtrace` help you?**

Been using ddtrace to investigate performance issues in this app, which has several separate services. Overall experience is very good — it's been easy to set up and helped us understand several issues.

**Environment**

* **ddtrace version:** 1.6.2 (does not occur in 1.5.0)
* **Configuration block (`Datadog.configure ...`):**

```Ruby
require 'ddtrace'

Datadog.configure do |c|
    c.tracing.instrument :rails, service_name: 'archivesspace'
end

```
* **Ruby version:** **jRuby** 9.2.21.0
* **Operating system:** Linux — Debian 12
* **Relevant library versions:**
See the "More log output" collapsed section above.

**Comment by ivoanjo** [comment] 2023-11-15 13:23
Thanks for reporting this one! The stack trace very much sounds like the issue reported in #2851 :thinking: . The other report was on regular CRuby so I think this is not JRuby-specific.

One workaround that may work, while the issue isn't fixed, is to disable startup logs by e.g. setting `DD_TRACE_STARTUP_LOGS=false` or via code:

```ruby
Datadog.configure do |c|
  c.diagnostics.startup_logs.enabled = false
end
```

If you can try the workaround above, do let us know if it worked for you

Hopefully this will allow you to run a more up-to-date ddtrace -- we do recommend going past 1.6.2 and jumping directly to the latest one.

**Comment by h4l** [comment] 2023-11-15 14:00
Hey, thanks for the workaround! I just realised I mixed up ddtrace version numbers above! I meant 1.15 rather than 1.5 and 1.16 rather than 1.6.

I just did some more testing and startup logs disabled I can't trigger the error on ddtrace 1.16.2, so that does seem to work.

It does look like the same issue. Strangely I still can't get it to trigger with ddtrace 1.15.0, so perhaps something changed to make it easier to trigger after 1.15?

**Comment by ivoanjo** [comment] 2023-11-15 15:17
> It does look like the same issue. Strangely I still can't get it to trigger with ddtrace 1.15.0, so perhaps something changed to make it easier to trigger after 1.15?

Indeed, that's probably the case :sweat_smile:  -- this is a highly timing-dependent bug/race. To be honest, looking at the changes between 1.15.0 and 1.16.2 I don't see anything that would be an obvious candidate for making this show up more often... :thinking:

**Comment by h4l** [comment] 2023-11-15 15:19
Yeah, I had a peek and couldn't see anything obvious! A hairy problem. Shall we close this as a duplicate of the issue you mentioned?

**Comment by ivoanjo** [comment] 2023-11-15 15:30
Duplicate of https://github.com/DataDog/dd-trace-rb/issues/2851

**Closed by ivoanjo** 2023-11-15 15:30 UTC
Labels: bug, community, tracing
