### ISSUE TITLE
Stack level too deep 

### ISSUE THREAD

**Issue by arunkumargit** [DataDog/dd-trace-rb#479] opened 2018-07-09 18:03 UTC
I have installed ddtrace gem in my rails application and at times I get stack level too deep error. I tried the latest version of ddtrace and downgraded to 0.12.1 still no luck. 

`SystemStackError (stack level too deep):
  /var/www/html/aktivlearn/vendor/bundle/ruby/2.1.0/gems/ddtrace-0.12.1/lib/ddtrace/contrib/rails/action_controller_patch.rb:56`

**Comment by delner** [comment] 2018-07-10 14:25
Hey @arunkumargit can you give me some more details? What version of `ddtrace` are you running? Can you also provide your Gemfile.lock to see if there are any conflicts? And how does this appear in your application? Does it appear on every route or just a few? If the latter, what makes that route unique?

**Comment by delner** [comment] 2018-08-06 15:35
@arunkumargit We didn't find any conditions that we could reproduce this issue with. I'm going to close this for now, but feel free to follow up if you have some more context to share!

**Closed by delner** 2018-08-06 15:35 UTC
Labels: bug, community

**Comment by mileszs** [comment] 2019-05-13 17:54
@delner I'm going to jump in on this one, as I am receiving the same error. Here's a stack trace from my tests.

```

  1) ThingChartsController#show when user is authorized returns success
     Failure/Error: get :show, params: { thing_id: thing.id, format: :json }

     SystemStackError:
       stack level too deep
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/registry.rb:27:in `synchronize'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/registry.rb:27:in `[]'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/extensions.rb:52:in `fetch_integration'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/extensions.rb:33:in `[]'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/utils.rb:60:in `datadog_configuration'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/utils.rb:16:in `normalize_template_name'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/core_extensions.rb:55:in `render_template_with_datadog'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/jb-0.6.0/lib/jb/action_view_monkeys.rb:48:in `render_template'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/core_extensions.rb:80:in `render_template_with_datadog'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/jb-0.6.0/lib/jb/action_view_monkeys.rb:48:in `render_template'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/core_extensions.rb:80:in `render_template_with_datadog'
     # ... goes on in this manner for quite a while
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/core_extensions.rb:80:in `render_template_with_datadog'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/jb-0.6.0/lib/jb/action_view_monkeys.rb:48:in `render_template'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/core_extensions.rb:42:in `block (2 levels) in render_with_datadog'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/core_extensions.rb:93:in `with_datadog_span'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/core_extensions.rb:42:in `block in render_with_datadog'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/tracer.rb:318:in `trace'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/core_extensions.rb:38:in `render_with_datadog'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/ddtrace-0.23.2/lib/ddtrace/contrib/rails/action_controller_patch.rb:49:in `process_action'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/rails-controller-testing-1.0.2/lib/rails/controller/testing/template_assertions.rb:61:in `process'
     # /Users/mileszs/.gem/ruby/2.6.2/gems/rails-controller-testing-1.0.2/lib/rails/controller/testing/integration.rb:12:in `block (2 levels) in <module:Integration>'
     # ./spec/controllers/thing_charts_controller_spec.rb:15:in `block (4 levels) in <top (required)>'
```

Configuration:

```
require "ddtrace"
Datadog.configure do |c|
  c.tracer enabled: Rails.env.production?
  c.use :rails
end
```

```
source 'https://rubygems.org'
ruby '2.6.2'

gem 'rails', '~> 5.2.3'

gem 'acts_as_list', '~> 0.9.10'
gem 'aws-sdk-s3', '~> 1.16.0'
gem 'bcrypt', '~> 3.1.7'
gem 'closure_tree', '~> 6.6.0'
gem 'data_uri', '~> 0.1.0'
gem 'errawr-rails', '~> 1.0.0'
gem 'honeybadger', '~> 4.0'
gem 'jbuilder', '~> 2.5'
gem 'jwt', '~> 2.1.0'
gem 'kaminari', '~> 1.1.0'
gem 'mail_whitelist', '~> 1.1.0'
gem 'olive_branch', '~> 2.1.5'
gem 'paper_trail', '~> 9.2.0'
gem 'pg', '~> 1.0.0'
gem 'puma', '~> 3.0'
gem 'pundit', '~> 1.1.0'
gem 'rack-cors'
gem 'sidekiq', '~> 5.2.0'
gem 'sidekiq-scheduler', '~> 3.0.0'
gem 'soulless', '~> 1.2.1'
gem 'jb', '~> 0.6'
gem 'wicked_pdf', git: 'https://github.com/mileszs/wicked_pdf.git'
gem 'combine_pdf'
gem 'flipper-active_record'
gem 'nokogiri', '~> 1.10.1'
gem 'ddtrace'

if ENV['INCLUDE_FACTORY_BOT'] == 'true'
  gem 'factory_bot_rails'
end

if ENV['INCLUDE_FAKER'] == 'true'
  gem 'faker'
end

group :development, :test do
  gem 'brakeman', require: false
  gem 'byebug', platform: :mri
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'rspec-rails'
  gem 'rubycritic'
  gem 'timecop'
end

group :test do
  gem 'database_cleaner'
  gem 'json_matchers'
  gem 'shoulda-matchers', '4.0.0.rc1'
  gem 'rails-controller-testing'
  gem 'simplecov', require: false
end

group :development do
  gem 'guard-rspec', require: false
  gem 'listen', '~> 3.1.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
```

If I remove `c.use :rails` from the configuration, it works fine. Even if I add `c.use :active_record`, it will still work fine—no errors. It's the `c.use :rails` in particular that seems to be the issue (I assume from patching into the rendering flow). 

The app is in `api_only` mode. I haven't seen documentation to indicate that makes a difference, but if I missed it, I do apologize. For fun, I set `config.api_only = false`, and still received the error.

Any help you can provide would be greatly appreciated! We're hoping to stick with DataDog as our one-stop shop for both infrastructure and APM metrics, and any other service reliability related tooling.

**Comment by delner** [comment] 2019-05-13 18:03
This is likely because `ddtrace` and (possibly) `jb-0.6.0` both use method rewrites, which causes a conflict that results in this loop.

Best way around this is to use a `prepend` strategy to patch instead. I've started refactoring the Rails integration with the intent of making this upgrade, but it probably won't be available for a little while. Unfortunately I really can't offer a workaround in the interim, other than to disable `jb` or `use :rails`. But rest assured this is on our radar to fix.

**Comment by mileszs** [comment] 2019-05-13 20:35
@delner Ah, cool. We're not heavily relying upon `jb`, so I'll just convert files in that format back to `jbuilder`.

That seems to resolve the issue, by the way. Thank you for the quick response.

**Comment by delner** [comment] 2019-05-14 19:50
Cool, glad to hear that helps. I'd also check the `jb` implementation, and see if its rewriting methods like `ddtrace` is. If they are, you might want to reach out to the authors, suggest they also change this like we are (to use `prepend`.)
