### ISSUE TITLE
The net/http integration doesn't annotate requests that raise exceptions

### ISSUE THREAD

**Issue by djmb** [DataDog/dd-trace-rb#888] opened 2019-12-17 15:52 UTC
If a net/http request raises an exception (e.g. `Net::OpenTimeout`), then the span is not annotated with tags from the request.

See: https://github.com/DataDog/dd-trace-rb/blob/ba583b5538c1cf39359094e39bb1b1a42fabbcec/lib/ddtrace/contrib/http/instrumentation.rb#L55

`annotate_span!` is called after the request completes and will be missed if an exception is raised. Since some of the annotations rely on having a response it should maybe be split into two parts, one called before the request is issued and one after.

**Comment by marcotc** [comment] 2019-12-17 18:27
Thank you @djmb for this report.

I was able to create a [test case to reproduce the issue](https://github.com/DataDog/dd-trace-rb/compare/fix/net-http-error-handling).

We'll follow up if we need more information, but I believe the problem is clearly defined here.

**Comment by delner** [comment] 2019-12-17 19:57
Makes sense to me, thanks for the report @djmb!

**Comment by marcotc** [comment] 2020-01-22 21:20
👋  @djmb, we've just released [v0.32.0](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.32.0) that includes a fix for this issue.

Let us know if the problem still persists after these changes.

**Closed by marcotc** 2020-01-22 21:20 UTC
Labels: bug, community, integrations
