### ISSUE TITLE
Ruby OpenTracing implementation fails to capture traces (sampling issue?)

### ISSUE THREAD

**Issue by azuretek** [DataDog/dd-trace-rb#822] opened 2019-09-19 22:14 UTC
I switched from Jaeger to Datadog for my tracing implementation, I wasn't seeing any traces show up in Datadog but I could see them being created and written by enabling debug/trace mode on the tracer lib and the agent.

I have this configured in my initializers folder.

```ruby
  tags = { 'env' => Rails.env }
  sampler = Datadog::RateSampler.new(datadog_config.sample_rate)
  OpenTracing.global_tracer = Datadog::OpenTracer::Tracer.new

  Datadog.configure do |c|
    c.tracer debug: true, enabled: true, hostname: datadog_config.trace_host, port: datadog_config.trace_port, sampler: sampler, partial_flush: true, tags: tags

    c.analytics_enabled = true
    c.runtime_metrics_enabled = true
    c.runtime_metrics statsd: Datadog::Statsd.new(datadog_config.statsd_host, datadog_config.statsd_port)
  end

  OpenTracing.global_tracer.datadog_tracer.default_service = service_name
```

I enabled the rails integration to validate if it was just OpenTracing or tracing in general and it looks like it's just OpenTracing. I validated the only differences between the OpenTracing and integration implementations is that the `Metrics` key is different or empty.

Traces that show up in Datadog look like this
```
Name: ApiV2::TasksController#index
Span ID: 6818616195376644571
Parent ID: 0
Trace ID: 8149720410364221083
Type: web
Service: Abis-MacBook-Pro.local
Resource: GET
Error: 0
Start: 1568918463840708096
End: 1568918463963661056
Duration: 122953000
Allocations: 14860
Tags: [
   system.pid => 30842,
   component => rack,
   span.kind => server,
   http.method => GET,
   http.url => /foo,
   env => development,
   http.status_code => 200]
Metrics: [ _dd1.sr.eausr => 1.0],
```

Traces that do not look like this
```
Name: ApiV2::TasksController#index
Span ID: 6818616195376644571
Parent ID: 0
Trace ID: 8149720410364221083
Type: web
Service: Abis-MacBook-Pro.local
Resource: GET
Error: 0
Start: 1568918463840708096
End: 1568918463963661056
Duration: 122953000
Allocations: 14860
Tags: [
   system.pid => 30842,
   component => rack,
   span.kind => server,
   http.method => GET,
   http.url => /foo,
   env => development,
   http.status_code => 200]
Metrics: [ _sampling_priority_v1 => 1.0],
```

The `SAMPLING_PRIORITY_KEY` is set wrong or not at all for OpenTracing traces, changing it to `_dd1.sr.eausr` seems to have solved all my issues.

I created a fork of this repo with the necessary changes, I'm not sure if this is a problem with the library or something that needs to be resolved on the Datadog service side.

https://github.com/getoutreach/dd-trace-rb/tree/fix_sampler

**Comment by delner** [comment] 2019-09-19 23:35
Thanks for the report @azuretek! The issue we're looking at might be more related to sampling priority than to metrics sample rate tag.

For reference:

 - `_sampling_priority_v1` determine whether a trace should be kept or discarded; we use it ensure distributed traces are sampled the same way as they cross process boundaries. If these values are not propagated correctly, traces can end up dropped. Values greater than 0 mean the trace should be kept, values less than or equal to 0 mean the trace should be dropped.
 - `_dd1.sr.eausr` determines the sample rates for trace search and analytics; its presence/absence will not cause traces to drop, only in the worst case to not be available in search & analytics.

It's inadvisable to substitute one of these tags for the other, as they do not serve the same function.

That aside, it'll be important to see what OpenTracing traces are not making it through. I have a few places we could look first:

 - You'll want to take a look at your agent logs, and if possible, put them in debug mode. If the agent is dropping traces, it generally will log it and explain why it dropped the trace. This is where trace validation is performed, so this is typically where you'll look first for errors related to malformed traces.
 - Examine the debug output from the Ruby tracer for any errors while flushing. It usually outputs `Writing N spans` followed by the full output of the trace; we'll want to examine all the spans in that trace for anything suspicious, as well as see if it wrote any errors while flushing.
 - From your configuration, it doesn't look like you're utilizing our Rails instrumentation with OpenTracing. Can you share the source of your Rails instrumentation so we can see how its generating spans?

Besides those spots, after casually examining your output from above, I noticed your span names look like `ApiV2::TasksController#index` which contain special characters. I suspect that the agent might be dropping spans for this reason. (Though I can't use this to explain why swapping metric tags would have any effect)

I actually don't recommend using this kind of name as a `span.name` with Datadog APM. In our trace model, `span.name` is a generic operation name that describes what would typically be considered a function, and excludes domain-specific criteria, e.g. `rack.request` or `action_view.render_partial`. Instead, you'd likely want to assign `ApiV2::TasksController#index` to `span.resource`, which acts user-domain driven value, and is broadly permissive of all kinds of values.

Another way of thinking about this is that `span.name` and `span.resource` act as dimensions similar to `GROUP_BY span.name, span.resource`.

This is a common point of confusion and the names of these fields don't intuitively suggest this behavior. Hopefully [this glossary](https://docs.datadoghq.com/tracing/visualization/) will explain how these fields affect the use of APM a bit more clearly.

**Comment by azuretek** [comment] 2019-09-20 02:54
As I described in my initial post, I did use debug mode on both the library and agent and there were no errors reported with any of my traces at the agent or the library. You can see what I changed in my branch to resolve this problem, I have no reason to lie about the behavior.

In my testing I did replace `span.name` with just `foo` and still could not see my traces in Datadog until I made the changes in my branch.

We instrument our application using several gems and middlewares, for example:
```
module Middleware
  class FaradayTracer < Faraday::Middleware
    def call( env )
      span = OpenTracing.start_span("Faraday")

      OpenTracing.inject(span.context, OpenTracing::FORMAT_RACK, env.request_headers)
      span.set_tag( 'url', env[:url].to_s )
      span.set_tag( 'method', env[:method].to_s )
      span.set_tag( 'body', env[:body] )

      @app.call(env).on_complete do
        span.finish
      end
    end
  end
end
```

This works fine with other tracing systems like Jaeger and Zipkin.

Feel free to test this out yourself, you can see in my branch the changes I made and they definitely work. I'd also like to point out that the built-in integrations use `_dd1.sr.eausr`. I understand that `_sampling_priority_v1` is intended for distributed traces, but your implementation with OpenTracing incorrectly uses this value.

**Comment by delner** [comment] 2019-09-20 07:20
I took a look at the branch, but it doesn't explain why the OpenTracing implementation is improperly setting tags, if that is indeed the issue.

Looking through our own adapter for OpenTracing `ddtrace/opentracer`, the only place I can see where sampling priority is set at all is in the `Datadog::OpenTracer::RackPropagator` which invokes the `Datadog::HTTPPropagator`. However, this is not implicitly applied, but rather is invoked via `extract` by the OT instrumentation from the user's application.

To understand what the OT instrumentation is sending that could cause improper tags to be set, I would need to see the instrumentation's source code and accompanying input. That would allow me see the input entering Datadog's OT adapter, and ascertain where and why it isn't converting traces properly.

From the configuration supplied, it doesn't look like you're using our Rails instrumentation, so if you could share the OT instrumentation you did use, that would be helpful. If you have a small test or script I can use to recreate the scenario, that'd be even better and would definitely go a long way to understanding and fixing the issue.

Also after re-reading the original configuration, I would recommend omitting the `sampler` and `partial_flush` options. The use of a custom sampler might not behave well with priority sampling/context propagation and cause traces to drop, and the `partial_flush` option is an experimental feature and may not be stable. Generally speaking I would also consider simplifying the configuration as much as possible, see if it works, then re-activate features until the problem re-emerges.

**Comment by delner** [comment] 2019-09-20 07:24
Also, are these distributed traces? And what libraries do they instrument? Is it just Rack & Rails?

**Comment by azuretek** [comment] 2019-09-20 20:00
We're instrumenting several areas of our application, I've shown you a middleware and we mainly do it that way wherever possible. Essentially we just call `span = OpenTracing.start_span` and `span.finish` and wrap our execution between those two calls.

When I remove the sampler and `partial_flush` options my traces do appear as expected, the trace looks like this:

```
 Name: ActiveRecord::SchemaMigration Load
Span ID: 2781458649796822455
Parent ID: 0
Trace ID: 1633549759078288639
Type: custom
Service: Abis-MacBook-Pro.local
Resource: ActiveRecord::SchemaMigration Load
Error: 0
Start: 1569009008198949888
End: 1569009008201018880
Duration: 2069000
Allocations: 18
Tags: [
   system.pid => 60198,
   component => ActiveRecord,
   span.kind => client,
   db.user => outreach,
   db.instance => outreach_development,
   db.vendor => mysql2,
   db.connection_id => 70228029002000,
   db.cached => false,
   db.statement => SELECT `schema_migrations`.* FROM `schema_migrations`,
   db.type => sql,
   env => development]
Metrics: [ _dd1.sr.eausr => 1.0]]
```

Not sampling in staging may be ok but we're emitting 10s of thousands in just minutes. Our production environments will probably be in the millions unless we can sample properly.

**Comment by delner** [comment] 2019-09-20 20:20
Ah, alright. Are these traces long running? Just trying to get a sense of the distribution of your spans; if you're producing millions of small traces, or smaller numbers of huge traces (each with many thousands of spans), or some blend of both.

The Ruby tracer & agent by default should reasonably handle large numbers of small traces, with the option to scale up further by implementing UDS with the agent. You can, if you wish, activate client side sampling in the tracer to reduce the volume of traces too, which should be safe to do.

The tracer/agent are currently more limited when dealing with traces with very large numbers of spans which produce large flushes (typically from long-running jobs); `partial_flush` was a feature we supplied to help address this, but isn't quite working right in the Ruby tracer right now (hence I think why disabling it alleviated your issue.) We're working on alternatives to better address this kind of scenario.

**Comment by azuretek** [comment] 2019-09-20 20:23
We have a pretty big variance, some are single spans, some have hundreds or thousands of spans.

The `partial_flush` setting doesn't seem to have any impact at all. It looks like the `sampler` is what's causing our spans to not show up on the datadog side, so we can't sample on the client side which is probably going to be an issue.

**Comment by delner** [comment] 2019-09-20 20:38
If it's isolated to the sampler, can you share a configuration code snippet I can experiment with to reproduce? And does it only happen with OpenTracing enabled? If it's just a swap of the sampler, and it occurs without OT, I should be able to setup it up in my test environment and take a deeper dive.

**Comment by azuretek** [comment] 2019-09-20 21:06
The configuration I've provided should be able to reproduce the problem.

**Comment by delner** [comment] 2019-09-20 21:35
I can't reproduce the issue with what was provided originally, as I don't have the OT instrumentation you're using that produces the spans in question. The Faraday middleware example you provided is helpful, but it doesn't cover the Rack/Rails traces in question.

I have also tested the our OT implementation in my own Rails test application and have produced spans without issue:

```ruby
### config/initializers/datadog.rb
require 'ddtrace'

Datadog.configure do |c|
  c.tracer debug: true
end

### config/initializers/opentracing.rb
require 'opentracing'
require 'ddtrace'
require 'ddtrace/opentracer'

# Activate the Datadog tracer for OpenTracing
OpenTracing.global_tracer = Datadog::OpenTracer::Tracer.new

### config/application.rb
require 'rack/tracer'

module DdRailsTest
  class Application < Rails::Application
    # Activate OpenTracing for Rack
    config.middleware.use Rack::Tracer
  end
end
```

Gemfile.lock:

```
PATH
  remote: /vendor/dd-trace-rb
  specs:
    ddtrace (0.27.0)
      msgpack

...

GEM
  remote: https://rubygems.org/
  specs:
    ...
    dogstatsd-ruby (4.0.0)
    msgpack (1.3.1)
    opentracing (0.4.3)
    rack (2.0.4)
    rack-tracer (0.8.0)
      opentracing (~> 0.4)
    rails (5.1.4)
      actioncable (= 5.1.4)
      actionmailer (= 5.1.4)
      actionpack (= 5.1.4)
      actionview (= 5.1.4)
      activejob (= 5.1.4)
      activemodel (= 5.1.4)
      activerecord (= 5.1.4)
      activesupport (= 5.1.4)
      bundler (>= 1.3.0)
      railties (= 5.1.4)
      sprockets-rails (>= 2.0.0)
```

![Screenshot from 2019-09-20 17-31-01](https://user-images.githubusercontent.com/3237131/65360106-a0da8e80-dbcc-11e9-92b4-67843948bdc0.png)

If there's a set files of configuration, instrumentation, and Gemfile you can provide me, that would help a ton with reproducing the issue in my test application.

**Comment by azuretek** [comment] 2019-09-20 22:42
Yes, when we don't have the sampler configured it works fine, we are also using the `rack-tracer` gem.

Try adding the `sampler` and set your sample rate to `1.0` to see the problem I'm describing.

```ruby
  sampler = Datadog::RateSampler.new(datadog_config.sample_rate)
  OpenTracing.global_tracer = Datadog::OpenTracer::Tracer.new

  Datadog.configure do |c|
    c.tracer debug: true, sampler: sampler
  end
```

**Comment by delner** [comment] 2019-09-21 00:30
So I just tried this, and had an interesting result.

When I configure the Datadog tracer with the sampler first, then set `OpenTracing.global_tracer`:

```ruby
require 'ddtrace'

Datadog.configure do |c|
  sampler = Datadog::RateSampler.new(1.0)
  c.tracer debug: true, sampler: sampler
end

require 'opentracing'
require 'ddtrace/opentracer'

# Activate the Datadog tracer for OpenTracing
OpenTracing.global_tracer = Datadog::OpenTracer::Tracer.new

```



 I get:

```
D, [2019-09-21T00:16:43.753878 #1] DEBUG -- ddtrace: [ddtrace] (/vendor/dd-trace-rb/lib/ddtrace/tracer.rb:371:in `write') Writing 1 spans (enabled: true)
D, [2019-09-21T00:16:43.754205 #1] DEBUG -- ddtrace: [ddtrace] (/vendor/dd-trace-rb/lib/ddtrace/tracer.rb:374:in `write') [
 Name: GET
Span ID: 6793187635666589366
Parent ID: 0
Trace ID: 292502370049783925
Type: 
Service: rails
Resource: GET
Error: 0
Start: 1569025003749992448
End: 1569025003753759488
Duration: 3767016
Allocations: 1734
Tags: [
   system.pid => 1,
   component => rack,
   span.kind => server,
   http.method => GET,
   http.url => /db,
   http.status_code => 200]
Metrics: [ ]]
```

But when I set `OpenTracing.global_tracer` then configure the Datadog tracer with the sampler:

```ruby
require 'opentracing'
require 'ddtrace'
require 'ddtrace/opentracer'

# Activate the Datadog tracer for OpenTracing
OpenTracing.global_tracer = Datadog::OpenTracer::Tracer.new

Datadog.configure do |c|
  sampler = Datadog::RateSampler.new(1.0)
  c.tracer debug: true, sampler: sampler
end
```

I get:

```
D, [2019-09-21T00:17:54.690909 #1] DEBUG -- ddtrace: [ddtrace] (/vendor/dd-trace-rb/lib/ddtrace/tracer.rb:371:in `write') Writing 1 spans (enabled: true)
D, [2019-09-21T00:17:54.691225 #1] DEBUG -- ddtrace: [ddtrace] (/vendor/dd-trace-rb/lib/ddtrace/tracer.rb:374:in `write') [
 Name: GET
Span ID: 1488273574720967508
Parent ID: 0
Trace ID: 6330773678160644581
Type: 
Service: rails
Resource: GET
Error: 0
Start: 1569025074687115264
End: 1569025074690799872
Duration: 3684625
Allocations: 1740
Tags: [
   system.pid => 1,
   component => rack,
   span.kind => server,
   http.method => GET,
   http.url => /db,
   http.status_code => 200]
Metrics: [ _sampling_priority_v1 => 1.0]]
```

Notice the addition of ` _sampling_priority_v1 => 1.0` in the second case. However in both cases, I still receive traces, so unfortunately it doesn't replicate your issue.

**Comment by delner** [comment] 2019-09-21 00:42
Okay I think the clue here is that  load order matters. We have this hook that updates the default tracer when OT's global tracer is set:

```ruby
def global_tracer=(tracer)
  super.tap do
    if tracer.class <= Datadog::OpenTracer::Tracer
      # Update the Datadog global tracer, too.
      Datadog.configuration.tracer = tracer.datadog_tracer
    end
  end
end
```

And since the `Datadog::OpenTracer::Tracer` instantiates its own tracer, the default Datadog tracer will be replaced by a different copy of `Datadog::Tracer`, without the settings applied previously in `Datadog.configure` which applies settings to that default tracer.

You probably could get around this by passing the `instance` option to `c.tracer`, e.g. `Datadog.configure { |c| c.tracer instance: OpenTracing.global_tracer.datadog_tracer }`, but then you'd have to initiate the OT tracer first anyways, so it probably wouldn't matter.

Anyways, not sure this is a factor in your issue, but it is something worth considering.

**Comment by azuretek** [comment] 2019-09-23 16:36
I don't know what to tell you, my traces aren't showing up despite the agent saying they're being written. When I'm using `gem 'ddtrace', '~> 0.27.0'` my OpenTracing instrumented traces don't show up at all. Whether or not I specify a sampler or not.

The traces look like this and the agent does appear to get them and send them to datadog.

```
D, [2019-09-23T09:32:25.968627 #96397] DEBUG -- ddtrace: [ddtrace] (/Users/abirenhart/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/ddtrace-0.27.0/lib/ddtrace/tracer.rb:371:in `write') Writing 1 spans (enabled: true)
D, [2019-09-23T09:32:25.969122 #96397] DEBUG -- ddtrace: [ddtrace] (/Users/abirenhart/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/ddtrace-0.27.0/lib/ddtrace/tracer.rb:374:in `write') [
 Name: redis.sadd
Span ID: 8901126964858651752
Parent ID: 0
Trace ID: 4867329074837723933
Type:
Service: Abis-MacBook-Pro.local
Resource: redis.sadd
Error: 0
Start: 1569256345966998016
End: 1569256345968411904
Duration: 1414000
Allocations: 57
Tags: [
   system.pid => 96397,
   span.kind => client,
   component => ruby-redis,
   db.type => redis,
   db.statement => sadd bento1a:requeue:delay_queues alert_close,
   db.instance => 13,
   peer.address => redis://redis-cache.outreach-dev.com:6379,
   env => development,
   bento => bento1a,
   application_version => eb40dcb8]
Metrics: [ _sampling_priority_v1 => 1.0]]
```

When I instrument using `c.use rails` it does work, but the only difference I can see between the two traces is the `Metrics` key.

**Comment by delner** [comment] 2019-09-23 17:15
Where in the UI are you looking for this trace? If you're looking in the Service view, maybe you're not seeing it because you have multiple top-level span names (e.g. traces with root spans who have different names, e.g. `redis.sadd`, `ApiV2::TasksController#index` etc.) The service page shows the most common top-level span name by default, which might explain why you're not seeing it.

**Comment by azuretek** [comment] 2019-09-23 17:17
I'm in the `Trace Search & Analytics` section, but also they don't show up on the `Services` page or `Trace List`, it looks like they're just not being captured at all by Datadog despite the agent saying it's sending to Datadog just fine.

**Comment by delner** [comment] 2019-09-23 17:20
If the agent says its successfully sent, then its almost certainly been captured, its just a question of whether the UI is making it visible or whether its being sampled on the backend.

We can take a look at your account and see if the latter is the case, but in the interest of protecting sensitive information, I'd recommend opening a support ticket to share this information (feel free to link this issue or mention me by name as well.)

**Comment by delner** [comment] 2019-12-20 15:11
Hey @azuretek, I'm going to close this issue for now; please feel free to follow up with a support ticket if you need any direct assistance.

**Closed by delner** 2019-12-20 15:11 UTC
